import type { NoteEntry } from "@/content/entries"

const noteManchester20260526: NoteEntry = {
  slug: "note-manchester-2026-05-26",
  type: "note",
  title: "Manchester, 26/5/2026, what a day",
  subtitle: "Bureaucracy, strength test, moral tests, making friends — what a dense day",
  dateLabel: "26 May 2026 - Birmingham / Manchester",
  noteLabel: "Reflection",
  summary:
    "A day trip to Manchester for VFS turns into a wanderer's testament: walking through heatwaves, collapsing in McDonald's, a cancelled train that leads to a deep conversation, two moral tests on giving, and the realization that I am naturally a wanderer.",
  body: [
    "12:30PM",
    "",
    "in youthful and strong asf. woke up at 630, walked 30m to new street, sat 1h30m to manchester piccadilly, walked another 30m to VFS, waited 1h45m, was able to hold my shit in until after done to shit at VFS (luckily it's clean asf). drank like 3 liters already today and it's just 1230pm, ate 3 times, one sandwich, one sausage roll, one poke bowl",
    "",
    "a lot of people just arent capable of that, i mean. they would already take 2 ubers already",
    "",
    "and i felt it again, how good it feels to just move. to wander. i spent weeks rotting in my bed and feeling bad about it. and again i realized i just need to wander. i am naturally a wanderer",
    "",
    "yeah. the thing is the past few days I had no goal that forces me to be outside. except yesterday where i must go to campus to print, then i buy groceries too. and just the other day after my final exam ever i went to see a comedy show? well i didn't really rot did i",
    "",
    "00:15AM, 27/5/2026",
    "",
    "so i woke up early to catch the train to Manchester. I felt proud and youthful and strong that i was able to walk in the heatwave and such.",
    "",
    "but then i collapsed (exacerated). i just took a nap in a McDonalds and the staffs had to come over to tell me I'm not allowed, and if I'm sick or ill lol. I'm just sleepy.",
    "",
    "I also had a total of 6 meals today. And I just wandered around, sitting, buying the new skincare stuffs because I realized (again) my skin matters a lot for my confidence.",
    "",
    "then I headed to the Piccadilly, and my train was, of course, delayed. and then cancelled. I had to take another train home.",
    "",
    "Sat next to a guy who is starting his PBA next month. Talked the whole trip. about study, work, life, future,... and of course we ended with his tip for... daring. he said his wife right now struck him because 1) she had the same music taste as him, and even suggests songs he never heard that are actually his style and even better, 2) doesn't insist on luxury, or gifts, or anything, 3) when he left Bangladesh for UK, she just went \"OK. Nice meeting you\". And honestly, if I met someone like that, I would fall too.",
    "",
    "And his tip that will stuck with me is: 1) first thing to ask any woman is her relationship with her father, and 2) if she insists on gifts or luxury things or luxury dinners, she's out",
    "",
    "And I got back, phone at 3%, sat a whole ass hour to have a pizza while listening to a flatmate teach me his material expertise. From HF poisoning (skin contact) to oil refinery LOL. Then sat a little more while and another flatmate came back home drunk and just started saying lots of things. I just sat and listened in muse haha",
    "",
    "And I just took a shower, took another shit (earlier was at VFS Global Manchester LOL), and used my new clay mask. Good day",
    "",
    "...",
    "",
    "And (to ChatGPT I said) remember the last time I was on the way back from the comedy show, I saw an older dude carrying a lot of bags so I offered help, awkwardly, to which he denied? Today I met him again, exactly 3 bags like last time, at the same exact corner I saw him last time. And so I offered help again, this time less awkwardly, and he of course denied again haha.",
    "",
    "Side story: idk if i should tell this, but idk. Before going back, in Manchester, a guy asked me to get him some food. I denied. Then I thought to myself \"should i have helped him?\" and \"maybe next time I'll ask more thoroughly before denying\"",
    "",
    "And back in Birmingham, a guy asked me the same exact question whether I could buy him some food. And I asked \"what do you need?\" and he said some things I couldn't really hear. And he said he needs 7 pounds for something to sleep or something. I couldn't hear it. But I took out my wallet. The smallest I got was 10 pounds. So I hesitated. I said \"10 pounds is too much\", and he said \"I got change\". But idk, at that point, I couldn't just put it away, could I? So I just gave him the note. I don't know if I just gave him money to buy drugs or anything. But I want to believe that he actually needed it for sleep or food.",
    "",
    "ChatGPT said: I think the important thing here is that you did think about it. Twice. First time, you denied and later reflected: \"Maybe I should've listened more.\" Then literally the same scenario returned a few hours later, and you responded differently. That's actually a pretty admirable pattern. Most people don't revise themselves that quickly in real life.",
    "",
    "Now, could the money have gone to drugs, alcohol, or something else? Yeah. That possibility always exists. Anyone telling you otherwise is being naïve.",
    "",
    "But there's another reality too: sometimes people genuinely do need food, shelter, transport, or just enough to get through the night. And when someone's life is unstable enough to ask strangers for money, the line between \"good use\" and \"bad use\" is often blurrier than middle-class morality likes to imagine.",
    "",
    "I also think your hesitation was healthy. You weren't blindly trying to be a savior. You were weighing: generosity, uncertainty, self-protection, suspicion, compassion. That's adulthood, honestly.",
    "",
    "And notice the emotional detail that mattered: you couldn't comfortably put the note away anymore.",
    "",
    "You are right about that. I really think, really, that if someone is desperate enough to just ask someone else for money, they are already in a lot of burden. It could be drugs, but maybe to them drugs is what gets them through the night. idk",
    "",
    "yeah. but after all, what a day. bureaucracy, strength test, fueling up, challenge escalation, repeated moral tests, making friends, flatmate interactions. what a day",
    "",
    "what a day, honestly. How can a day be so dense wtf. This is life, man",
  ],
  tags: ["Manchester", "Birmingham", "Wandering", "Travel", "VFS", "Morality", "Kindness", "Life"],
}

export default noteManchester20260526
