import type { NoteEntry } from "@/content/entries"

const noteGeometryOfBrotherhood: NoteEntry = {
  slug: "note-geometry-of-brotherhood",
  type: "note",
  title: "Greater Good and Sportsmanship",
  subtitle: "From Illuminati to Sportsmanship",
  dateLabel: "22:52 8 May 2026",
  noteLabel: "Reflection",
  summary:
    "A train of thoughts spanning Illuminati, AI, privacy, greed, religion, and the beautiful balance between competition and sportsmanship.",
  body: [
    "The Illuminati and the Greater Good",
    "I always knew the Illuminati was real and the Rothschild is part of it. The Triangle society something, with all the most powerful men in the world.",
    "But if there was, what if they are actually trying to do the 'correct' thing? To transcend humanity. Even a genocide of most of the world is not objectively bad. At least it's good for the environment.",
    "",
    "The AI Mystic",
    "Recently, every time I get outputs from AI, whether chats or images, I feel like it's from another dimension. And yeah, it's probably just... math. LOL.",
    "But nothing says math is not actually the mystic. Math, in fact, is the only lens that human can use to see into the real world.",
    "Some say AI advancements are making people go into a collective hive mind by providing daily data, hopes, dreams,...",
    "And I don't see why that is wrong? Why do people care so much about data privacy?",
    "",
    "The Transparent Self",
    "Like I always felt, even in a daily human to human interaction, being transparent, to the point of 'weird' to the normal social norms, is desirable. Why wouldn't I want that?",
    "The only reason is that someone would use it against me. To exploit, to steal,...",
    "And that's a recurring theme in my world view. The word is 'greed'. The world would honestly be better off without greed. At least that's what I think. You know it.",
    "I think it's somewhat because the world itself was built on privacy, specifically private property norms, that sharing is so hard to be taken as the norm. I, on the other hand, tend to share.",
    "In short, yes, I don't think sharing my data to AI companies (a massive concern today) is inherently bad. If they use it for good, it's fine. But what even is good?",
    "",
    "The Common Thread",
    "That brought me back to religion. The two biggest religions I know, Christianity and Buddhism, if anything, taught a thing in common: Treat others well. We are all just brothers and sisters.",
    "That drives everything downstream. No competitive thoughts or actions. And I like that. I tend to want to practice that in my daily life.",
    "But the reason why that even needs to be 'taught' at all is, I believe, somewhat, humans are inherently competitive.",
    "",
    "Sportsmanship",
    "Without even starting with corporations which is a recent phenomenon, look at sports. We love to compete ever since the dawn of humanity.",
    "But 'competing' is not the only thing. It's also sportsmanship. To compete, yet to not see each other as enemies. To still help others out when in need.",
    "And I think, sportsmanship is the nicest thing to have. You play your heart out, and still love with your heart.",
    "I think this is the first time I ever articulate this view and this exact word, while it seems to align almost too perfectly with my worldview. And it really opens a perspective I haven't seen for a long time.",
    "",
    "Love, Yet Compete",
    "I love, yes. But I still can and should compete.",
    "Recently, I tend to let my 'lovefulness' take over and be afraid what others might think, that if they feel behind or not. And I... reduce myself to it.",
    "But what I really should do, tho, is to be the best version of myself. Compete. Try to win the 'competition', whatever that might be. The corporate ladder, travel the world, fame, strength, health,... And still be humble and love people.",
    "Because, honestly, who doesn't love a famous jacked genius that makes filthy money, and still stay humble?",
    "That has always been what I wanted to be. Balancing study, intellectual exploration, cutting-edge tools, while still trying to stay in shape and read,... all that.",
  ],
  tags: ["Illuminati", "AI", "Privacy", "Greed", "Religion", "Competition", "Sportsmanship", "Philosophy", "Identity", "Language"],
}

export default noteGeometryOfBrotherhood